    # VPC
    EC2VPC:
        DeletionPolicy: "Delete"
        Type: "AWS::EC2::VPC"
        Properties:
            CidrBlock: "10.22.0.0/16"
            EnableDnsSupport: true
            EnableDnsHostnames: true
            InstanceTenancy: "default"
            Tags: 
              - 
                Key: "Name"
                Value: !Sub "$to2-vpc"

    # Subnets
    EC2Subnet:
        DeletionPolicy: "Delete"
        Type: "AWS::EC2::Subnet"
        Properties:
            AvailabilityZone: !Sub "${AWS::Region}a"
            CidrBlock: "10.22.1.0/24"
            VpcId: !Ref EC2VPC
            MapPublicIpOnLaunch: false
            Tags: 
              - 
                Key: "Name"
                Value: !Sub "$to2-public-subnet-a"

    EC2Subnet2:
        DeletionPolicy: "Delete"
        Type: "AWS::EC2::Subnet"
        Properties:
            AvailabilityZone: !Sub "${AWS::Region}c"
            CidrBlock: "10.22.2.0/24"
            VpcId: !Ref EC2VPC
            MapPublicIpOnLaunch: false
            Tags: 
              - 
                Key: "Name"
                Value: !Sub "$to2-public-subnet-c"
                
     EC2Subnet3:
        DeletionPolicy: "Delete"
        Type: "AWS::EC2::Subnet"
        Properties:
            AvailabilityZone: !GetAtt EC2Subnet3.AvailabilityZone
            CidrBlock: "10.22.101.0/24"
            VpcId: !Ref EC2VPC
            MapPublicIpOnLaunch: false
            Tags: 
              - 
                Key: "Name"
                Value: !Sub "$to2-private-subnet-a"

    EC2Subnet4:
        DeletionPolicy: "Delete"
        Type: "AWS::EC2::Subnet"
        Properties:
            AvailabilityZone: !GetAtt EC2Subnet4.AvailabilityZone
            CidrBlock: "10.22.102.0/24"
            VpcId: !Ref EC2VPC
            MapPublicIpOnLaunch: false
            Tags: 
              - 
                Key: "Name"
                Value: !Sub "$to2-private-subnet-c"
    
    # NACL
    EC2NetworkAcl:
        DeletionPolicy: "Delete"
        Type: "AWS::EC2::NetworkAcl"
        Properties:
            VpcId: !Ref EC2VPC

    # EIP
    EC2EIP:
        DeletionPolicy: "Delete"
        Type: "AWS::EC2::EIP"
        Properties:
            Domain: "vpc"
            Tags: 
              - 
                Key: "Name"
                Value: !Sub "$to2-eip"

    # NAT Gateway
    EC2NatGateway:
        DeletionPolicy: "Delete"
        Type: "AWS::EC2::NatGateway"
        Properties:
            SubnetId: !Ref EC2Subnet
            Tags: 
              - 
                Key: "Name"
                Value: !Sub "$to2-nat"
            AllocationId: !GetAtt EC2EIP.AllocationId

    # Internet Gateway
    EC2InternetGateway:
        DeletionPolicy: "Delete"
        Type: "AWS::EC2::InternetGateway"
        Properties:
            Tags: 
              - 
                Key: "Name"
                Value: !Sub "$to2-igw"

    # Route Tables
    EC2RouteTable:
        DeletionPolicy: "Delete"
        Type: "AWS::EC2::RouteTable"
        Properties:
            VpcId: !Ref EC2VPC
            Tags: 
              - 
                Key: "Name"
                Value: !Sub "$to2-public-rt"

    EC2RouteTable2:
        DeletionPolicy: "Delete"
        Type: "AWS::EC2::RouteTable"
        Properties:
            VpcId: !Ref EC2VPC
            Tags: 
              - 
                Key: "Name"
                Value: !Sub "$to2-private-rt"

    EC2RouteTable3:
        DeletionPolicy: "Delete"
        Type: "AWS::EC2::RouteTable"
        Properties:
            VpcId: !Ref EC2VPC
            Tags: 
              - 
                Key: "Name"
                Value: !Sub "$to2-vpc-rt"
