    DynamoDBTable:
        DeletionPolicy: "Delete"
        Type: "AWS::DynamoDB::Table"
        Properties:
            AttributeDefinitions: 
              - 
                AttributeName: "PK"
                AttributeType: "S"
              - 
                AttributeName: "SK"
                AttributeType: "S"
            BillingMode: "PAY_PER_REQUEST"
            TableName: "to2"
            KeySchema: 
              - 
                AttributeName: "PK"
                KeyType: "HASH"
              - 
                AttributeName: "SK"
                KeyType: "RANGE"