AWSTemplateFormatVersion: '2010-09-09'
Description: 'Parameterized Cognito User Pool and Client'

Parameters:
  ProjectName:
    Type: String
  CallbackURLs:
    Type: CommaDelimitedList
  LogoutURLs:
    Type: CommaDelimitedList

Resources:
  CognitoUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub "${ProjectName}-user-pool"
      AutoVerifiedAttributes: [email]
      Schema:
        - Name: nickname
          AttributeDataType: String
          Mutable: true
          Required: true
      UserPoolTags:
        Name: !Sub "${ProjectName}-user-pool"

  CognitoUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub "${ProjectName}-user-pool-client"
      UserPoolId: !Ref CognitoUserPool
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows: [code]
      AllowedOAuthScopes: [email, openid]
      CallbackURLs: !Ref CallbackURLs
      LogoutURLs: !Ref LogoutURLs

Outputs:
  CognitoUserPoolId:
    Value: !Ref CognitoUserPool
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolId"
  CognitoUserPoolClientId:
    Value: !Ref CognitoUserPoolClient
    Export:
      Name: !Sub "${AWS::StackName}-UserPoolClientId"